### ISSUE TITLE
mt6 farm

### ISSUE THREAD

**Issue by toastedmail** [msimerson/Mail-Toaster-6#120]
How would one have a setup where there are several mt6 servers and if anyone of the servers failed, the other servers would be performing all functions just as if no server failed and users would not know anything failed. 

Obviously the downed server would have to be replaced but no mail services would stop being available.

I would think yahoo and gmail amoungst others have their mail systems set up like this.,

**Comment by msimerson** [comment]
> How would one have a setup where there are several mt6 servers

Stop thinking of servers and think instead of services. Have a pool of virus scanners, a pool of spam scanning servers, a pool of SMTP services, etc. Have each higher level service (example: webmail depends on dovecot, dovecot depends on access mailbox stores, etc.) depends on pools a layer below them. Each layer has redundancy and a well established API for accessing the service.

**Comment by toastedmail** [comment]
And where do these 'pools' of services reside?
