### ISSUE TITLE
Method to monitor Jails

### ISSUE THREAD

**Issue by Infern1** [msimerson/Mail-Toaster-6#155]
In the past munin was used to monitor the jail activity and host information.
I can't see this anymore in the MT6 version.

Is there no need to trend, load, disk usage, nginx, php and mysql usage over time?

**Comment by msimerson** [comment]
> Is there no need to trend, load, disk usage, nginx, php and mysql usage over time?

I wouldn't say that. The issue is that putting monitoring apps inside [many of] the jails tramples all over the gains (simplicity, security, composability) made by thinly provisioning the services. Ideally, every jail has only the software inside that it needs, is ephemeral, and costs us nothing when it's replaced (which is why we have data partitions).

One of the issues I didn't want to deal with in MT6 was having to update/reprovision a whole raft of jails / hosts because of a perl / module vulnerability that affected munin. Not to mention, having to install perl and all the munin modules in the jails. Rather than installing munin node many times, I'd much rather see the `monitor` jail larded up with munin and the client software (unbound, mysql-client, clamscan, etc.) needed to reach into the active service jails and extract the data to be measured. 

That's basically what I've done for myself, manually. For example, I manually copied the unbound control & server certificates into my [monitoring jail](http://jails.tnpi.net/monitor/monitor/index.html#dns) and then restored the DNS graphs. I've improved upon this in #156 by moving the control certificates to /data/control, and then the monitoring provision script can copy them into the monitoring jail, wherever it's convenient for the munin unbound plugins. 

The same sort of thing can be done for most of the servers.
