### ISSUE TITLE
Haraka deny excludes why not rspamd and spamassassin?

### ISSUE THREAD

**Issue by Infern1** [msimerson/Mail-Toaster-6#253]
### Observed behavior
In the default karma.ini rspamd and spamassassin are in the deny excludes list

https://github.com/haraka/haraka-plugin-karma/blob/5c881b0a684e2d36d47a926c5b17fbe72e3b222f/config/karma.ini#L60

However in this version they don't exist, what is the reason behind?

Side note:
avg is added although someone might decide not to install, but clamd is missing. So think this line need to be updated.

**Comment by msimerson** [comment]
Several reasons: When used with karma, I don't permit spamassassin or rspamd to reject because they both, on occasion (with an untrained rspamd being the worse of the two) throw false positives. If you've trained your rspamd and/or spamassassin and you're comfortable that their rejections are sound, then update accordingly.

When clamd has the Extras enabled, it too has a "too high" false positive rate. I think it's a reasonable default because a virus score will nearly always cause karma to reject. Again, peruse your logs/stats and decide if that's the right choice for you.

**Comment by Infern1** [comment]
clear answer, maybe add this to the FAQ ?

**Comment by msimerson** [comment]
I've added it to the haraka install page.
