### ISSUE TITLE
How to disable spamassassin check for haraka outgoing emails? Slow sending.

### ISSUE THREAD

**Issue by johannes73** [msimerson/Mail-Toaster-6#301]
We have a phpList mailing list, that sends about 1.100 emails per hour, through haraka. This is many times slower than we are used to, compared to when we earlier sent with qmail. 

I am a relatively new haraka user. I am not sure, but I think this slow speed could be because spamassassin checks every outgoing mail individually. 

So, I tried to disable spamassassin, by uncommenting this line:

# spamassassin

...in this file:
/data/haraka/config/plugins

And then I restarted the server.

But the speed is still the same... Do you guys see what I am doing wrong here? Very thankful for any tips how to get the speed up.

**Comment by msimerson** [comment]
Well, qmail is fast because it's not doing anything extra with the messages.

Are you sure it's SA that's slowing down the connection? I'd try disabling the dkim_sign, karma and AV plugins as well and measure speed. Then turn them back on one at a time and determine the performance cost of each plugin for your application.

**Comment by johannes73** [comment]
Thank you, Matt. You were right. When I disabled the following modules in /data/haraka/config/plugins, the sending speed from PhpList raised from 1.100 emails/hour, to about 25.000 emails/hour. I have not yet analyzed in detail the speedup for each disabled module, but I will try to do so in the next sends. 

Now I am thinking: is it possible to disable modules for just outgoing email, from certain accounts (newsletter lists)? 

The modules I disabled, before sending to the newsletter list:

clamd
avg
spamassassin
rspamd
dkim_sign
karma

**Comment by msimerson** [comment]
That's a sticky question. In general, you don't want your users to be propagating viruses, which is why it's advisable to have AV Scanning enabled for outbound. DKIM signing chews up a bit of CPU which, if your server isn't CPU beefy, could limit things. You could disable it for list traffic, but there's a better than average chance that could affect deliverability.

Disabling the anti-spam plugins (spamassassin, rspamd, karma) seems sensible enough for list traffic, but then you've got to invent the mechanism that does so. Someone [recently added](https://github.com/haraka/haraka-plugin-karma/pull/27) support for disabling the karma plugin. Something similar would need to be done for the anti-spam plugins. Maybe a single property like `connection.transaction.notes.no_antispam` that when set, would disable multiple plugins. Then create your own plugin that identifies such messages and sets that flag.
