### ISSUE TITLE
upgrade vpopmail on FreeBSD 13.3 

### ISSUE THREAD

**Issue by tniethammer** [msimerson/Mail-Toaster-6#583]
after upgrading vpopmail with "provision vpopmail" the script stops with error 

> 
> ***   enabling vpopmail MySQL access   ***
> 
> ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
> vpopmail db does not exist
> ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
> vpopmail db does not exist
> 
>    ***   creating mysql database vpopmail   ***
> 
> ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
> 

there is no mysql on localhost, the script should use the credentials from vpopmail.mysql config but I did not find any place in mysql.sh where you use the credentials

should there be some rdr rule which forward local requests to the mysql jail ?

I guess its an problem in include/mysql.sh at mysql_bin() function, there is the root password set but no Host is set
```
mysql_bin()
{
        if mysql_password_set; then
                echo "/usr/local/bin/mysql"
                return
        fi

        # set in toaster-watcher.conf
        if [ -n "$TOASTER_MYSQL_PASS" ]; then
                echo "/usr/local/bin/mysql --password=\"$TOASTER_MYSQL_PASS\""
                return
        fi

        echo "/usr/local/bin/mysql"
}

```

should install without error because database exists on local jail or on externenal mysql server 

OS: 13.3-RELEASE-p5
MT-Toaster:  20240319

**Comment by msimerson** [comment]
So, `provision/vpopmail.sh` is calling `include/mysql.sh` to first check if the vpopmail db exists in mysql, and if not, then create it. It's failing because TOASTER_MYSQL_PASS is unset or incorrectly set in mail-toaster.conf.

You're getting distracted by the hostname. It's showing as localhost because the build script is running the mysql commands against the mysql binaries *inside* the mysql jail, and thus it is localhost. Just look in `include/mysql.sh` and pay careful attention to the jexec prefixes.
