### ISSUE TITLE
Optimize Mysql provision with zfs recordsize

### ISSUE THREAD

**Issue by Infern1** [msimerson/Mail-Toaster-6#74]
Mysql with ZFS can be optimized, specially when working with InnoDB tables

See this reference: https://www.patpro.net/blog/index.php/2014/03/09/2617-mysql-on-zfs-on-freebsd/

So what needs to be done:
- create extra /data volumes with defined recordsize
- update my.cnf with the correct folders

**Comment by msimerson** [comment]
Now that I've looked into this further, I have a few thoughts:

1. no need to worry about MyISAM tables. New installs default to InnoDB. Most installs have very small amounts of data in MySQL, so optimizing brings precious little benefit for the added complexity. For those migrating old data, they can manually create a FS optimized for MyISAM if they care to. By putting their settings in /var/db/mysql/my.cnf, their customizations are automatically preserved.
2. The existing mysql data FS already has the correct blocksize for the InnoDB log files, so there's no need to change that FS.
3. That leaves only the InnoDB data file(s) that need their own optimally sized 16kb filesystem. Perhaps /data/mysql-innodb that gets mounted at /jails/mysql/data/innodb.
4. What happens when the log files are lost? Maybe just store them on /jails/mysql filesystem, and then size /data/mysql for innodb. This is extremely easy to implement. After a reprovision, the old log files are gone. If they matter, the log files could be copied to the new staged mysql during re-deployment.

**Comment by msimerson** [comment]
Closing, due to lack of activity. Feel free to reopen if progress begins.
